"""initial schema

Revision ID: 019950e6eb19
Revises: 
Create Date: 2026-10-04 19:39:13.045088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019950e6eb19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('phone', sa.Text(), server_default='', nullable=False),
    sa.Column('bio', sa.Text(), server_default='', nullable=False),
    sa.Column('expertise', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('notify_requests', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('show_message_previews', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('available', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','listener','moderator')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('users_role', 'users', ['role'], unique=False)
    op.create_index('users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('service_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('requester_id', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('listen','moderate')", name=op.f('ck_service_requests_kind')),
    sa.CheckConstraint("status IN ('pending','accepted','rejected')", name=op.f('ck_service_requests_status')),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('fk_service_requests_provider_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_service_requests_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_requests')),
    sa.UniqueConstraint('room_id', name=op.f('uq_service_requests_room_id'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('request_sent','request_received','request_update')", name=op.f('ck_notifications_kind')),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_notifications_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('notifications_user_created', 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('notifications_user_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('NOT read'))
    op.create_table('request_approvals',
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.CheckConstraint("state IN ('pending','accepted','rejected')", name=op.f('ck_request_approvals_state')),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_request_approvals_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_request_approvals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'user_id', name=op.f('pk_request_approvals'))
    )
    op.create_table('request_participants',
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_request_participants_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_request_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', 'user_id', name=op.f('pk_request_participants'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('requester_id', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('listen','moderate')", name=op.f('ck_rooms_kind')),
    sa.CheckConstraint("status IN ('pending','active','closed','rejected')", name=op.f('ck_rooms_status')),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], name=op.f('fk_rooms_provider_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], name=op.f('fk_rooms_request_id_service_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_rooms_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('request_id', name=op.f('uq_rooms_request_id'))
    )
    op.create_index('rooms_provider', 'rooms', ['provider_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_messages_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('messages_room_created', 'messages', ['room_id', 'created_at'], unique=False)
    op.create_table('room_closures',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_closures_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_closures_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_closures'))
    )
    op.create_table('room_members',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    op.create_index('room_members_user', 'room_members', ['user_id'], unique=False)
    op.create_table('room_mutes',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_mutes_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_mutes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_mutes'))
    )
    op.create_table('room_ratings',
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('by_id', sa.Text(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), server_default='', nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name=op.f('ck_room_ratings_stars')),
    sa.ForeignKeyConstraint(['by_id'], ['users.id'], name=op.f('fk_room_ratings_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_ratings_room_id_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'by_id', name=op.f('pk_room_ratings'))
    )
    op.create_table('message_stars',
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_stars_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_stars_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name=op.f('pk_message_stars'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_stars')
    op.drop_table('room_ratings')
    op.drop_table('room_mutes')
    op.drop_index('room_members_user', table_name='room_members')
    op.drop_table('room_members')
    op.drop_table('room_closures')
    op.drop_index('messages_room_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('rooms_provider', table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('request_participants')
    op.drop_table('request_approvals')
    op.drop_index('notifications_user_unread', table_name='notifications', postgresql_where=sa.text('NOT read'))
    op.drop_index('notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('service_requests')
    op.drop_index('users_username_lower', table_name='users')
    op.drop_index('users_role', table_name='users')
    op.drop_index('users_email_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
